In [1]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from statsmodels.stats.weightstats import ttest_ind 
from statsmodels.distributions.empirical_distribution import ECDF

In [2]:
#set up
sns.set(style='whitegrid')

In [4]:
#load dataset
df = pd.read_csv('data/customer_data.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  100000 non-null  int64
 1   age                 100000 non-null  int64
 2   gender              100000 non-null  object
 3   income              100000 non-null  int64
 4   education           100000 non-null  object
 5   region              100000 non-null  object
 6   loyalty_status      100000 non-null  object
 7   purchase_frequency  100000 non-null  object
 8   purchase_amount     100000 non-null  int64
 9   product_category    100000 non-null  object
 10  promotion_usage     100000 non-null  int64
 11  satisfaction_score  100000 non-null  int64
dtypes: int64(6), object(6)
memory usage: 9.2+ MB

In [6]:
df.head()

   id  age  gender  income   education  ... purchase_frequency purchase_amount product_category  promotion_usage satisfaction_score
0   1   27    Male   40682    Bachelor  ...           frequent           18249            Books                0                  6
1   2   29    Male   15317     Masters  ...               rare            4557         Clothing                1                  6
2   3   37    Male   38849    Bachelor  ...               rare           11822         Clothing                0                  6
3   4   30    Male   11568  HighSchool  ...           frequent            4098             Food                0                  7
4   5   31  Female   46952     College  ...         occasional           19685         Clothing                1                  5

[5 rows x 12 columns]

In [7]:
df['purchase_amount'] = df['purchase_amount'].astype('float').round(2)
df.head()

   id  age  gender  income   education  ... purchase_frequency purchase_amount product_category  promotion_usage satisfaction_score
0   1   27    Male   40682    Bachelor  ...           frequent         18249.0            Books                0                  6
1   2   29    Male   15317     Masters  ...               rare          4557.0         Clothing                1                  6
2   3   37    Male   38849    Bachelor  ...               rare         11822.0         Clothing                0                  6
3   4   30    Male   11568  HighSchool  ...           frequent          4098.0             Food                0                  7
4   5   31  Female   46952     College  ...         occasional         19685.0         Clothing                1                  5

[5 rows x 12 columns]

In [8]:
#decriptive statistic
desc_stats = df[['income', 'purchase_amount', 'satisfaction_score']].describe()
desc_stats

              income  purchase_amount  satisfaction_score
count  100000.000000    100000.000000       100000.000000
mean    27516.269880      9634.790840            5.009650
std     12996.782587      4799.339449            1.038714
min      5000.000000      1118.000000            0.000000
25%     16271.750000      5583.000000            4.000000
50%     27584.500000      9452.000000            5.000000
75%     38747.250000     13350.000000            6.000000
max     50000.000000     26204.000000           10.000000

In [13]:
male_purchase = df[df['gender'] == 'Male']['purchase_amount']
female_purchase = df[df['gender'] == 'Female']['purchase_amount']
t_stat, p_value, _ = ttest_ind(male_purchase, female_purchase, usevar='unequal')
print(t_stat)
print(p_value)

0.025486774705113416
0.979666748175195

In [ ]:
#confidence interval for statistical score of highest income quartile
q3_income = df['income'].quantile(0.75)